install:
	./install.sh

start:
	./start.sh

stop:
	./stop.sh

test:
	./test.sh

direct:
	./direct-am-test.sh "how much battery left"

telegram:
	./run-telegram.sh

perms:
	chmod +x bridge.py telegram_bot.py start.sh stop.sh test.sh run-telegram.sh direct-am-test.sh termux-boot-start.sh termux-setup-permissions.sh
